#pragma once
#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 0
#define ENGINE_VERSION_PATCH 1
#define ENGINE_BUILD_NUMBER 48
#define ENGINE_BUILD_DATE "2025-10-15 16:25:40"
#define ENGINE_BUILD_TYPE "Debug"
#define ENGINE_VERSION_STR "0.0.1"
#define ENGINE_VERSION_FULL_STR "0.0.1.48"
